[package]
name = "bluetooth_mesh"
version = "0.1.0"
authors = ["Andrew <andrew@gilbrough.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
slotmap = "0.4.0"
aes = "0.3.2"
aead = "0.2.0"
crypto-mac = "0.7.0"
dbl = "0.2.1"
block-modes = "0.3.3"
subtle = "2.2.2"